name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']
        laravel: ['11.*']
        prefer: ['prefer-stable']
        include:
          - laravel: '11.*'
            testbench: '9.*'
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php }}-

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev
        composer update --${{ matrix.prefer }} --prefer-dist --no-interaction --dev

    - name: Setup in-cluster config
      run: |
        sudo mkdir -p /var/run/secrets/kubernetes.io/serviceaccount
        echo "some-token" | sudo tee /var/run/secrets/kubernetes.io/serviceaccount/token
        echo "c29tZS1jZXJ0Cg==" | sudo tee /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        echo "default" | sudo tee /var/run/secrets/kubernetes.io/serviceaccount/namespace
        sudo chmod -R 777 /var/run/secrets/kubernetes.io/serviceaccount/

    - name: Run test suite
      run: composer run-script test
